"""empty message

Revision ID: 1fbe3d01e182
Revises: 
Create Date: 2026-05-17 20:47:01.256652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbe3d01e182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_lookup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_lookup', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
