"""empty message

Revision ID: 2053b9924bab
Revises: 1fbe3d01e182
Create Date: 2026-05-18 02:00:32.137606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2053b9924bab'
down_revision = '1fbe3d01e182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('alarms_prescription_detail_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'prescriptions', ['prescription_id'], ['prescription_id'])
        batch_op.drop_column('prescription_detail_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_detail_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alarms_prescription_detail_id_fkey'), 'prescription_details', ['prescription_detail_id'], ['prescription_detail_id'])
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###
