"""initial

Revision ID: 2b233fb728a5
Revises: 
Create Date: 2026-05-17 14:56:35.263468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b233fb728a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.alter_column('circle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_circle_members_circle'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_circle_members_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'circles', ['circle_id'], ['circle_id'])

    with op.batch_alter_table('med_lookup', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_med_lookup_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('med_supply', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_med_supply_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)

    with op.batch_alter_table('med_supply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_med_supply_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('med_lookup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_med_lookup_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_circle_members_user'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_circle_members_circle'), 'circles', ['circle_id'], ['circle_id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('circle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
