"""empty message

Revision ID: 5e1912808b74
Revises: e06fdcaf5ac6
Create Date: 2026-05-19 21:41:00.106306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1912808b74'
down_revision = 'e06fdcaf5ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prescription_details_lookup_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('prescription_details_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('lookup_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lookup_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('prescription_details_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('prescription_details_lookup_id_fkey'), 'med_lookup', ['lookup_id'], ['lookup_id'])

    # ### end Alembic commands ###
