"""empty message

Revision ID: 6e82301b743b
Revises: 708b83dee5c2
Create Date: 2026-05-21 16:21:43.102420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e82301b743b'
down_revision = '708b83dee5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('alarm_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('onesignal_notification_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], name=op.f('alarms_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('alarm_id', name=op.f('alarms_pkey'))
    )
    # ### end Alembic commands ###
