"""empty message

Revision ID: 708b83dee5c2
Revises: 5e1912808b74
Create Date: 2026-05-20 23:29:38.186557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708b83dee5c2'
down_revision = '5e1912808b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarms')
    with op.batch_alter_table('circles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prescriptions', ['prescription_id'], ['prescription_id'])
        batch_op.drop_column('circle_name')

    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm_active', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('alarm_active')

    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))

    with op.batch_alter_table('circles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circle_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prescription_id')

    op.create_table('alarms',
    sa.Column('alarm_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('onesignal_notification_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], name=op.f('alarms_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('alarm_id', name=op.f('alarms_pkey'))
    )
    # ### end Alembic commands ###
