"""empty message

Revision ID: 8bd96679da2a
Revises: 2b233fb728a5
Create Date: 2026-05-17 16:15:54.084654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd96679da2a'
down_revision = '2b233fb728a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_end', sa.DateTime(), nullable=True))
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('date_end')
        batch_op.drop_column('date_start')

    # ### end Alembic commands ###
