"""empty message

Revision ID: e06fdcaf5ac6
Revises: faf034438864
Create Date: 2026-05-19 21:23:48.679099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06fdcaf5ac6'
down_revision = 'faf034438864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supply_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'med_supply', ['supply_id'], ['supply_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supply_id')

    # ### end Alembic commands ###
