"""add lookup_id and user_id to prescription_details

Revision ID: faf034438864
Revises: 2053b9924bab
Create Date: 2026-05-19 19:51:28.004248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf034438864'
down_revision = '2053b9924bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lookup_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('prescription_details_supply_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'med_lookup', ['lookup_id'], ['lookup_id'])
        batch_op.drop_column('supply_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supply_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prescription_details_supply_id_fkey'), 'med_supply', ['supply_id'], ['supply_id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('lookup_id')

    # ### end Alembic commands ###
